"""webhook_delivery cascade FK

Revision ID: 5f14ae51a2da
Revises: 91b0a11e1148
Create Date: 2026-05-30 14:35:58.306532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f14ae51a2da'
down_revision: Union[str, Sequence[str], None] = '91b0a11e1148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('webhook_deliveries_user_id_fkey'), 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_deliveries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_deliveries_user_id_fkey'), 'webhook_deliveries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
