"""i18n + jsonb + layout + corrections

Revision ID: d23dc5298229
Revises: 5f14ae51a2da
Create Date: 2026-05-30 15:20:58.905594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd23dc5298229'
down_revision: Union[str, Sequence[str], None] = '5f14ae51a2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('layout', sa.String(), nullable=True))
    op.add_column('history', sa.Column('output_lang', sa.String(length=2), nullable=True))
    op.add_column('history', sa.Column('corrected_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # Convert existing JSON-string text into real JSONB. Use postgresql_using so
    # Postgres knows how to cast existing rows; otherwise the ALTER fails.
    op.alter_column('history', 'result_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True,
               postgresql_using='result_json::jsonb')
    op.alter_column('templates', 'schema_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False,
               postgresql_using='schema_json::jsonb')
    op.add_column('users', sa.Column('preferred_lang', sa.String(length=2), nullable=True))
    # GIN index on result_json for future search ("find all extractions of doc_type X").
    op.create_index('ix_history_result_gin', 'history', ['result_json'],
                    postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_result_gin', table_name='history')
    op.drop_column('users', 'preferred_lang')
    op.alter_column('templates', 'schema_json',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('history', 'result_json',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('history', 'corrected_json')
    op.drop_column('history', 'output_lang')
    op.drop_column('history', 'layout')
    # ### end Alembic commands ###
